import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List
from app.config import settings
from app.models import ActionItem


class EmailService:
    """Service to send action items via email"""
    
    @staticmethod
    def create_html_email(
        actions: List[ActionItem],
        meeting_title: str = None,
        meeting_date: str = None
    ) -> str:
        """
        Create HTML formatted email with action items
        
        Args:
            actions: List of action items
            meeting_title: Optional meeting title
            meeting_date: Optional meeting date
            
        Returns:
            HTML string for email body
        """
        html = """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 800px; margin: 0 auto; padding: 20px; }
                .header { background-color: #4F46E5; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
                .header h1 { margin: 0; font-size: 24px; }
                .content { background-color: #f9fafb; padding: 20px; border-radius: 0 0 8px 8px; }
                .meeting-info { background-color: white; padding: 15px; border-radius: 6px; margin-bottom: 20px; }
                .action-item { background-color: white; padding: 15px; margin-bottom: 12px; border-radius: 6px; border-left: 4px solid #4F46E5; }
                .action-owner { font-weight: bold; color: #4F46E5; margin-bottom: 5px; }
                .action-task { color: #374151; margin-bottom: 8px; }
                .action-meta { font-size: 12px; color: #6B7280; }
                .priority-high { border-left-color: #EF4444; }
                .priority-medium { border-left-color: #F59E0B; }
                .priority-low { border-left-color: #10B981; }
                .footer { text-align: center; color: #6B7280; font-size: 12px; margin-top: 20px; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>📋 Meeting Action Items</h1>
                </div>
                <div class="content">
        """
        
        # Add meeting info if available
        if meeting_title or meeting_date:
            html += '<div class="meeting-info">'
            if meeting_title:
                html += f'<div><strong>Meeting:</strong> {meeting_title}</div>'
            if meeting_date:
                html += f'<div><strong>Date:</strong> {meeting_date}</div>'
            html += '</div>'
        
        # Add action items
        html += f'<h2 style="color: #1F2937; margin-bottom: 15px;">Action Items ({len(actions)})</h2>'
        
        for i, action in enumerate(actions, 1):
            priority_class = ""
            if action.priority:
                priority_class = f"priority-{action.priority.lower()}"
            
            html += f'<div class="action-item {priority_class}">'
            html += f'<div class="action-owner">👤 {action.owner}</div>'
            html += f'<div class="action-task">{action.task}</div>'
            
            meta_parts = []
            if action.priority:
                html += f'<span class="action-meta">🎯 Priority: {action.priority.capitalize()}</span>'
            if action.deadline:
                html += f'<span class="action-meta" style="margin-left: 15px;">📅 Deadline: {action.deadline}</span>'
            
            html += '</div>'
        
        html += """
                </div>
                <div class="footer">
                    <p>Generated by Meeting Action Tracker</p>
                    <p>This is an automated email. Please do not reply.</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        return html
    
    @staticmethod
    async def send_email(
        recipients: List[str],
        subject: str,
        html_content: str
    ) -> dict:
        """
        Send email to recipients
        
        Args:
            recipients: List of email addresses
            subject: Email subject
            html_content: HTML content for email body
            
        Returns:
            Dictionary with success status and message
        """
        if not settings.smtp_username or not settings.smtp_password:
            return {
                "success": False,
                "message": "Email credentials not configured"
            }
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = settings.smtp_username
            msg['To'] = ', '.join(recipients)
            msg['Subject'] = subject
            
            # Attach HTML content
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            # Send email
            with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
                server.starttls()
                server.login(settings.smtp_username, settings.smtp_password)
                server.send_message(msg)
            
            return {
                "success": True,
                "message": f"Email sent successfully to {len(recipients)} recipient(s)",
                "sent_to": recipients
            }
            
        except Exception as e:
            return {
                "success": False,
                "message": f"Failed to send email: {str(e)}",
                "sent_to": []
            }